name: Test
on:
  - push
  - pull_request

jobs:
  test:
    name: Run tests
    strategy:
      fail-fast: false
      matrix:
        php:
          - 7.4
          - 8.0
          - 8.1
          - 8.2
          - 8.3
          - 8.4
        phpunit:
          - "^8"
          - "^9"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - name: Add PHPUnit from matrix
        run: |
          composer require --dev phpunit/phpunit:${{ matrix.phpunit }}
      - name: Run PHPCS
        run: ./vendor/bin/phpcs -p -n
      - name: Run PHPSTAN
        run: ./vendor/bin/phpstan analyse
